### ISSUE TITLE
I think u must be DdoS attacked xD

### ISSUE THREAD

**Issue by Taki21** [ImagicalGamer/GoAwayTaki#1]
Lol...U really were inspired by me xD! Give me full credit for this plugin since my names on it lollllololol

**Comment by ImagicalGamer** [comment]
xD. This has no reference to you xP.

**Comment by ImagicalGamer** [comment]
xP

**Comment by XShockinFireX** [comment]
lol

**Comment by Sandertv** [comment]
Best name ever

**Comment by Taki21** [comment]
Lol After doing some DdOs Exams I will be ready to attack xD

1738 hours Later

Message From Webpage: @Taki21 has Officially DdOs Attacked You! Return To Safety! 
xD
